In [17]:
import tensorflow as tf


In [66]:
tf.set_random_seed(666)

#### 1b

In [67]:
x = tf.random_uniform([],minval = -1, maxval = 1)
y = tf.random_uniform([],minval = -1, maxval = 1)

In [69]:
res = tf.case({tf.less(x,y):lambda:tf.add(x,y),
               tf.greater(x,y):lambda:tf.subtract(x,y)}, 
               default=lambda:tf.zeros([]), exclusive = True)

#### 1c

In [106]:
x = tf.constant([[0,-2,-1],[0,1,2]])
y = tf.zeros_like(x)

In [109]:
z = tf.equal(x,y)

In [114]:
z.eval()

array([[ True, False, False],
       [ True, False, False]])

#### 1d

In [115]:
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
 30.97266006,  26.67541885,  38.08450317,  20.74983215,
 34.94445419,  34.45999146,  29.06485367,  36.01657104,
 27.88236427,  20.56035233,  30.20379066,  29.51215172,
 33.71149445,  28.59134293,  36.05556488,  28.66994858])

In [118]:
y = tf.where(tf.greater(x,30))

In [121]:
z = tf.gather(x,y)

In [122]:
z.eval()

array([[31.190735],
       [30.97266 ],
       [38.084503],
       [34.944454],
       [34.45999 ],
       [36.01657 ],
       [30.20379 ],
       [33.711494],
       [36.055565]], dtype=float32)

#### 1e

In [125]:
diag = tf.range(1,7)

In [129]:
mtx = tf.diag(diag)

In [130]:
mtx.eval()

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]], dtype=int32)

#### 1f

In [131]:
mtx = tf.random_uniform(shape = (10,10), minval = 1, maxval = 5)

In [133]:
mtx.eval()

array([[1.1915479, 4.110331 , 4.2585063, 2.8757024, 2.6782322, 1.0084434,
        4.126271 , 4.236641 , 1.0528026, 2.8564076],
       [3.5653057, 4.406308 , 2.1378994, 1.4737806, 3.0728793, 3.273902 ,
        4.8367805, 2.745163 , 4.067738 , 3.847805 ],
       [2.0686707, 4.0223064, 4.851686 , 4.8620963, 3.0565639, 1.8134003,
        3.2602005, 3.1974363, 1.1134825, 2.6297417],
       [1.6865206, 2.780902 , 3.5361795, 4.7717853, 3.4355078, 1.0533943,
        2.5227718, 4.930747 , 2.8951297, 1.8600268],
       [1.4521408, 3.8164692, 1.1890659, 4.0443583, 1.0048347, 2.822784 ,
        3.873321 , 4.1142044, 2.2272205, 1.7635646],
       [4.342115 , 2.9940743, 1.0696268, 2.1479983, 3.8974857, 2.0118885,
        2.5293064, 4.7924604, 4.691124 , 4.363459 ],
       [2.977439 , 3.43926  , 1.4010258, 2.8729615, 4.990742 , 2.210723 ,
        1.0170546, 2.1858974, 3.783351 , 1.9209156],
       [2.4293222, 3.6757412, 1.0699825, 1.1978283, 2.682695 , 1.2716751,
        1.69561  , 2.3435674, 4.14585

In [132]:
dtm = tf.matrix_determinant(mtx)

In [134]:
dtm.eval()

52271.188

#### 1g

In [135]:
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])

In [140]:
y, idx = tf.unique(x)

In [141]:
y.eval()

array([ 5,  2,  3, 10,  6,  4,  1,  0,  9], dtype=int32)

#### 1h

In [167]:
x = tf.random_normal(shape = [3])
y = tf.random_normal(shape = [3])

In [168]:
z = tf.subtract(x,y)

In [169]:
mean = tf.reduce_mean(z)

In [170]:
res = tf.cond(mean < 0, lambda: tf.square(z - mean), lambda: tf.reduce_sum(tf.abs(z)))

In [189]:
res.eval()

array([10.628155  ,  8.397588  ,  0.13120788], dtype=float32)

In [ ]:
sess.close()